# Oinarrizko teoria
Atal hau [@Pitaevskii] liburuan oinarrituta dago. Aztertuko ditugu oinarrizko gauzak GPE ekuazioa ulertu ahal izateko.

## Ez-uniforme Bose gasak T=0K

Ikertuko ditugu Bose gas diluituen dinamika.

### Gross-Pitaevskii ekuazioa (GPE)

Elektromagnetismoan egiten dugun bezala, $\hat{\Psi}(\mathbf{r}, t)$ eremu eragilea eremu klasiko batekin, $\Psi_0(\mathbf{r}, t)$, ordezkatuko dugu. Azken honi kondentsatuaren uhin-funtzioa edo ordena-parametroa deitzen zaio. Orain behar dugu ekuazio bat duena funtzio klasikoaren dinamika. Hau lortzeko gogoratu Heisemberg-en irudian hurrengo erlazioa bete behar duela $\hat{\Psi}$:

$$
i\hbar \frac{\partial}{\partial t} \hat{\Psi}(\mathbf{r}, t) = [\hat{\Psi}(\mathbf{r}, t), \hat{H}]
$$

$$
= \left[ -\frac{\hbar^2 \nabla^2}{2m} + V_{ext}(\mathbf{r}, t) + \int \hat{\Psi}^\dagger(\mathbf{r}', t) V(\mathbf{r}' - \mathbf{r}) \hat{\Psi}(\mathbf{r}', t) d\mathbf{r}' \right] \hat{\Psi}(\mathbf{r}, t),
$${#eq-p1}

non $V_{ext}(\mathbf{r}, t)$ kanpo-potentziala den eta $V(\mathbf{r}' - \mathbf{r})$

Aldaketa egin ahal izateko, Bornen hurbilketa bete beharko da. Honetarako $V_{eff}$ bete beharko ditu energia txikiko sakabanaketaren baldintzak eta $\Psi_0$ era motelean aldatuko da elkarrekintza-potentzialaren barrutian. Hau betetzen bada $\mathbf{r'}$ $\mathbf{r}$-rekin aldatu dezakegu. 

$$
i\hbar \frac{\partial}{\partial t} \Psi(\mathbf{r}, t) = \left( -\frac{\hbar^2 \nabla^2}{2m} + V_{ext}(\mathbf{r}, t) + g|\Psi(\mathbf{r}, t)|^2 \right) \Psi(\mathbf{r}, t)
$${#eq-GPE}

non ordena-parametroa $g = \int V_{eff} \; d\mathbf{r}$ den. Hau s-wave sakabanaketaren $a$ parametroaren funtzioan jar dezakegu:

$$
g = \frac{4 \pi \hbar^2 a}{m}
$${#eq-p3}

non $a$ s-uhinen sakabanatze-luzera den eta $m$ atomo baten masa.

Hau izango da Maxwell ekuazioen analogoa baina energia eta momentuaren erlazioa fotoiena izan beharrean De Brogliren erlazioa beteko dute.

Zenbait baldintza bete beharko dira @eq-GPE erabili ahal izateko.

* BEC-a sortzeko partikula kopuru handia behar ditugu.
* Temperatura txikia izatea behar dugu partikulen artean sortzen diren elkarrekintzak txikiak izateko.
* Gure uhin funtzioa dago normalizatuta hurrengo moduan: $\int |\Psi|^2 \; d\mathbf{r} = N$
* Ekuazioa bete egingo da $\mathbf{r} \gg a$ denean.

Hau guztia betetzen bada, gasaren dentsitatea kondentzatuarenarekin bat etorriko da:

$$
n(\mathbf{r}) = |\Psi(\mathbf{r})|^2
$${#eq-density}

Beste era bat izango da egoera estazionario bat inposatzen

$$
\delta \left[ -i\hbar \int \Psi^* \frac{\partial}{\partial t} \Psi \, d\mathbf{r}dt + \int E \, dt \right] = 0
$${#eq-p5}

akzioari. Honekin izango dugun ekuazioa

$$
i\hbar \frac{\partial \Psi(\mathbf{r}, t)}{\partial t} = \frac{\delta E}{\delta \Psi^*(\mathbf{r}, t)}
$${#eq-p6}

izango da, non energia funtzionalaren ordena-parametroa

$$
E = \int \left( \frac{\hbar^2}{2m}|\nabla\Psi|^2 + V_{ext}(\mathbf{r})|\Psi|^2 + \frac{g}{2}|\Psi|^4 \right) d\mathbf{r}
$${#eq-p7}

Orain ikusiko ditugu [@eq-GPE]-ren kontserbazio legeak. Lehenengo, kontuan izanda $\int |\Psi|^2 \; d\mathbf{r} = N$ dela, hau da, partikula kopurua konstante mantentzen dela. Beraz, [@eq-GPE] $\Psi^*$-rekin biderkatuz probabilitatearen kontserbazio legea lortzen da:

$$
\frac{\partial n}{\partial t} + \text{div}\mathbf{j} = 0
$${#eq-kontinuidad}

non erabili dugun [@eq-density] eta sartu dugun korronte dentsitatea:

$$
\mathbf{j}(\mathbf{r}, t) = -\frac{i\hbar}{2m} (\Psi^* \nabla \Psi - \Psi \nabla \Psi^*) = n \frac{\hbar}{m} \nabla S
$${#eq-korrontea}

non $S$ ordena-parametroaren fasea den. Gogoratu, ordena-parametroa funtzio konplexua izanda honela idatzi dezakegula:

$$
\Psi(\mathbf{r},t) = \sqrt{n(\mathbf{r},t)}e^{i S(\mathbf{r},t)}.
$${#eq-uf}

Ekuazio honetatik lortu ahal dugu zein den kondentsatuaren abiadura fasearen bitartez:

$$
\mathbf{v_s}(\mathbf{r},t) = \frac{\hbar}{m} \nabla S.
$${#eq-abiadura}

Gainera, ikusi dezakegunez hau irrotazionala izango da, zentsua daukana, azkenean superfluido guztiek propietate hau erakusten baitute.

Jakinda energia ere kontserbatu egingo dela lortu ahal izango dugu momentu dentsitatearen ekuazioa.

$$
m \frac{\partial j_i}{\partial t} + \frac{\partial \Pi_{ik}}{\partial x_k} = -n \frac{\partial V_{ext}}{\partial x_i},
$${#eq-momentu-kontserbazioa}

non

$$
\Pi_{ik} = \frac{\hbar^2}{4m^2} \left[ \frac{\partial \Psi}{\partial x_i} \frac{\partial \Psi^*}{\partial x_k} - \Psi \frac{\partial^2 \Psi^*}{\partial x_i \partial x_k} + \text{c.c.} \right] + \frac{gn^2}{2} \delta_{ik},
$${#eq-momentu-tentsorea}

momentuaren fluxu tentsorea da. Ohartu, kanpo indar barik momentua kontserbatu egingo dela.

Erabilgarria da fasearentzako ekuazio bat lortzea. Hau lortzen da [@eq-uf] [@eq-GPE] sartuz: 

$$
\hbar \frac{\partial}{\partial t} S + \left( \frac{1}{2} m \mathbf{v}_s^2 + V_{ext} + gn - \frac{\hbar^2}{2m\sqrt{n}} \nabla^2 \sqrt{n} \right) = 0.
$${#eq-S}

Konturatu [@eq-density] eta [@eq-S] osatzen dutela ekuazio multzo bat analogoa dena GPE ekuazioarekin. $\hbar$ ekuazioan sartzen da dentsitatearen gradientearen bitartez, honi deitzen zaio "presio kuantikoa".

[@eq-GPE]-ren soluzio geldikorra forma simple bat du

$$
\Psi(\mathbf{r},t) = \Psi_0(\mathbf{r}) e^{-\frac{i\mu t}{\hbar}}.
$${#eq-guf}

Denboraren menpekotasuna potentzial kimikoa zehazten du

$$
\mu = \frac{\partial E}{\partial N},
$${#eq-mu(E)}

guzti honekin Gross-Pitaevskii ekuazioa honela idatzi dezakegu

$$
\left( -\frac{\hbar^2 \nabla^2}{2m} + V_{ext}(\mathbf{r}) + g|\Psi_0(\mathbf{r})|^2 - \mu \right) \Psi_0(\mathbf{r}) = 0,
$${#eq-egonGPE}

non suposatu egin dugu gure potentziala ez dela denboraren menpekoa. $\mu$-ren balioa normalizazio baldintzak ezarriko digu.

### Thomas-Fermi limitea

[@eq-S] ekuazioan ikusi dugu parte bat presio kuantiko modukoa izango dela. Honek bi zatitan banatu dezakegu: $gn$ interakzio partean eta Bohm-en potentzialean ($Q$). Honen forma hurrengoa da:

$$
Q = - \frac{\hbar^2}{2m} \frac{\nabla^2 \sqrt{n}}{\sqrt{n}}.
$${#eq-Q}

Thomas-Fermi limitean, $\nabla^2 \sqrt{n}/\sqrt{n}$ magnitudea berreskuratze luzera $\xi = \hbar / \sqrt{2mgn}$ (hau erakusten du noiz izango dugun kondentsatua a la ez, oso txikia, edo orden berekoa, bada sistemaren luzera karakteristikoa interakzioak eta gero ez du denborarik berreskuratzeko eta apurtzen da kondentsatua) baino askoz handiagoa bada (hau da, $\sqrt{n}$ oso era motelean aldatzen bada denbora eta espazioan zehar) $Q$ guztiz arbuiagarria izango da eta berridatz dezakegu [@eq-S] abiadura eremu bat bezala:

$$
m \frac{\partial \mathbf{v}_s}{\partial t} + \nabla \left( \frac{1}{2}m\mathbf{v}_s^2 + V_{ext} + gn \right) = 0 
$${#eq-TF}

non ekuazio hau bat datorren Eulerren ekuazioarekin, fluido batentzat kanpo potentzial baten eraginean eta biskositate barik. Fluido honen presioa $P = gn^2/2$ eta soinuaren abiadura $c=\sqrt{gn/m}$. Horretaz gain, berridatzi dezakegu [@eq-kontinuidad] $\mathbf{v}_s$-ren menpean 

$$
\frac{\partial n}{\partial t} + \text{div}(v_sn) = 0,
$${#eq-kontinuidad_vs_rho}

ekuazio bikote hauek hurrengo atalean ikusiko dugunez superfluido baten hidrodinamikari datorkie.

Thomas-Fermi hurbilketan oinarrizko egoerak forma erreza hartzen du, $v_s = 0$. Hau da, energia zinetikoa guztiz arbuiatuz lortuko dugu. Era honetan izango dugu:

$$
gn(\mathbf{r}) + V_{ext}(\mathbf{r}) = \mu
$${#eq-5.23}

non $\mu$ oinarrizko egoerari dagokion potentzial kimikoa den. Kanpo eremurik ez daukagunean ailegatzen gara Bogoliubov erlazioari $\mu = gn$.
 
### Bortex interakzio txikiko Bose gasan

Esan dugunez, GPE deskribatuta dago [@eq-guf]-ren bitartez, hau da, magnitude orden bat denborarekiko menpekotasuna duena, non menpekotasuna fase global bat deskribatzen duen potentziak kimikoaren funtzioa dena.

Orain aztertuko ditugu bortez soluzioak. Hauek ematen dira gure kondentsatuaren dentsitatea zerorantz doanean. Hauek ematen diren eremuak, berreskuratze luzera baino txikiagoko eskualdetan gertatzen dira eta kontuan izan behar dugu presio kuantikoaren terminoa GPE-n. Normalean, azkar biratzen duen erreferentzia sisteman izango dira egonkorrak, sistema horretan energiaren funtzionala zero baita.

Superfluidoetan dauden biraketak ez dira solido zurrunean dauden bezalakoak $\mathbf{v} = \mathbf{\Omega} \times \mathbf{r}$, baizik eta deskribatuta egongo da bortizitatea difusioarekin: $\text{curl}\mathbf{v} = 2\mathbf{\Omega}$. Hau konturatzen bagara, kontraesan bat izango da superfluidoak irrotazionalak direla esan genuelako, hau da, espero dugu hauek ez biratzea solido zurruna bezala.

Demagun dugula $R$ erradioko eta $L$ luzerako zilindro batean gasa konfinatuta. Izango dugun soluzioa hurrengo formakoa izango da:

$$
\Psi_0(\mathbf{r}) = e^{is\varphi}|\Psi_0(r)|,
$${#eq-zuf}

non sartu ditugun koordenatu zilindrikoak $z$, $r$ eta $\varphi$. $s$ zenbaki osoa da, gure uhin-funtzioa balio bakarra izan dezan. Konturatzen bagara [@eq-zuf] $l_z$-ren autobalioa izango da $l_z = s \hbar$ izaten. Beraz, bortex osoaren momentu angeluarra $L_z = N s \hbar$ izango da. [@eq-zuf] adierazten du gas bat biratzen hurrengo abiadura tangentzialarekin

$$
v_s = \frac{\hbar}{m}\frac{s}{r}.
$${#eq-abiadura-tangen}

Konturatzen bagara hau guztiz desberdina da solido zurrunean geneukanarekin, hau $1/r$-ren proportzionala baita ([@fig-vel-eremuak]).

```{python}
#| echo: false
#| label: fig-vel-eremuak
#| fig-cap: "Abiadura-eremu tangentziala fluxu irrotazionalerako ($v_{\\text{irr}}$) eta errotazio rigidoko ($v_{\\text{rig}}$) fluxurako. Abiadura-eremu irrotazionala $1/r$ bezala dibergitzen da $r \\to 0$ denean. Hemen $r$ eta $v$ unitate arbitrarioetan (a.u.) neurtzen dira."
import numpy as np
import matplotlib.pyplot as plt
import scienceplots

# Configuración del estilo
plt.style.use(['science', 'notebook'])

# Definición de los datos
r = np.linspace(0.01, 5, 500)
v_rig = r           # Flujo de rotación rígida (v proportional to r)
v_irr = 1 / r       # Flujo irrotacional (v proportional to 1/r)

# Creación de la figura
fig, ax = plt.subplots(figsize=(6, 4))

# Graficar las líneas
ax.plot(r, v_irr, color='black', linewidth=1.5)
ax.plot(r, v_rig, color='black', linewidth=1.5)

# Configuración de límites y ticks
ax.set_xlim(0, 5)
ax.set_ylim(0, 5)
ax.set_xticks([0, 1, 2, 3, 4, 5])
ax.set_yticks([0, 1, 2, 3, 4, 5])

# Etiquetas de los ejes
ax.set_xlabel(r'$r$ [a.u.]')
ax.set_ylabel(r'$v$', rotation=0, labelpad=15)

# Anotaciones con flechas (posicionadas como en la imagen)
ax.annotate(r'$v_{\mathrm{irr}}$', xy=(0.3, 3.5), xytext=(1.2, 3.5),
            arrowprops=dict(arrowstyle='->', lw=0.8),
            va='center')

ax.annotate(r'$v_{\mathrm{rig}}$', xy=(3.0, 3.0), xytext=(3.9, 2.5),
            arrowprops=dict(arrowstyle='->', lw=0.8),
            va='center')

# Ajuste de los bordes (ticks hacia adentro y en todos los lados)
ax.tick_params(which='both', direction='in', top=True, right=True)

plt.show()
```

Ordezkatuz [@eq-zuf] [@eq-egonGPE], lortuko dugun adierazpena $|\Psi_0|$-rentzat:

$$
-\frac{\hbar^2}{2m} \frac{1}{r} \frac{d}{dr} \left( r \frac{d|\Psi_0|}{dr} \right) + \frac{\hbar^2 s^2}{2mr^2} |\Psi_0| + g|\Psi_0|^3 - \mu|\Psi_0| = 0.
$${#eq-20}

Bortexaren distantzia handietara dakigu izan behar dugun dentsitatea kondentsatuarena izango dela $|\Psi_0| \to \sqrt{n}$. Hau dela eta, sartuko dugu hurrengo funtzio adimensionala $f(\eta)$ eta gure dentsitatea:

$$
|\Psi_0| = \sqrt{n} f(\eta),
$${#eq-aduf}

non $\eta = r/\xi$ eta $\xi = \hbar / \sqrt{2mgn}$ berreskuratze luzera den. Funtzio honek betetzen duen ekuazioa

$$
\frac{1}{\eta} \frac{d}{d\eta} \left( \eta \frac{df}{d\eta} \right) + \left( 1 - \frac{s^2}{\eta^2} \right) f - f^3 = 0,
$${#eq-f}

non muga baldintzak $f(\eta\to\infty) = 1$ eta $f(0) = 0$ izan behar diren. Hau numerikoki ebasten badugu ikusten da ([@fig-bortex-profila]) nola $r$ $\xi$-ren ordenakoa denenean dentsitate aldaketa bortitza izango den.

```{python}
#| echo: false
#| label: fig-bortex-profila
#| fig-cap: "[@eq-f]-ren soluzio numerikoak $s=1$ eta $s=2$ kasuetarako. Ikusten da nola kondentsatuaren dentsitatea aldatzen den $\\eta$-ren funtzioan."

import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import solve_bvp
import scienceplots

# Estiloa aplikatu
plt.style.use(['science', 'notebook'])

def fun(eta, y, s):
    f, df = y
    # d2f/deta2 isolatuta ekuaziotik
    d2f = -(1/eta)*df - (1 - s**2/eta**2)*f + f**3
    return np.vstack((df, d2f))

def bc(ya, yb):
    # Mugalde baldintzak: f(0) = 0 eta f(inf) = 1
    return np.array([ya[0], yb[0] - 1])

# Parametroak
s = 1
eta_max = 10
eta = np.linspace(0.001, eta_max, 100) # 0.1etik hasten da singularitatea saihesteko

# Hasierako estimazioa
y1_guess = np.zeros((2, eta.size))
y1_guess[0] = 1 - np.exp(-eta) # Profil tipikoa

# Ebazpena
res1 = solve_bvp(lambda eta, y: fun(eta, y, s), bc, eta, y1_guess)

# Parametroak
s = 2

# Hasierako estimazioa
y2_guess = np.zeros((2, eta.size))
y2_guess[0] = 1 - np.exp(-eta) # Profil tipikoa

# Ebazpena
res2 = solve_bvp(lambda eta, y: fun(eta, y, s), bc, eta, y2_guess)


# Grafikoa osatu
fig, ax = plt.subplots(figsize=(6,4))

ax.plot(res1.x, res1.y[0], color='black', linewidth=1.5, label=r'$f(\eta)$')

ax.plot(res2.x, res2.y[0], color='black', linewidth=1.5, label=r'$f(\eta)$')

# Irudiaren dekorazioa
ax.set_xlabel(r'$\eta$')
ax.set_ylabel(r'$f(\eta)$', rotation=0, labelpad=20)
ax.set_xlim(0, 6)
ax.set_ylim(0, 1)

# Ticks konfigurazioa estiloaren arabera
ax.tick_params(direction='in', top=True, right=True)

# Anotazioa (flecha estiloa mantenduz)
ax.annotate(r'$s=1$', xy=(2, 0.8), xytext=(4, 0.6),
            arrowprops=dict(arrowstyle='->', lw=0.8))
ax.annotate(r'$s=2$', xy=(2, 0.4), xytext=(2.5, 0.2),
            arrowprops=dict(arrowstyle='->', lw=0.8))


plt.show()
```
## Superfluidotasuna 

Aipatu dugunez, BEC-a superfluido baten moduan jokatzen du tenperatura kritiko bat baino hotsago dagoenean. Parte honetan eztabaidatuko ditugu Landauren superfluidoen hidrodinamika, eta nola teoria honek ahalbidetzen dituen aurkitutako ordena-parametroaren fasearen fluktuazioak BEC-aren teorian.

### Landauren irizpidea superfluidotasunarentzako

Landauren superfluidoen teoria garatzeko, energiaren eta momentuaren transformazio Galilearrak erabiliko erabiliko ditugu. $E$ eta $\mathbf{P}$ izango dira energia eta momentua fluidoaren pausaguneko sisteman $K$. Orduan $K'$ sisteman, $\mathbf{v}$ abiaduraz mugitzen dena $K$ sistemarekiko, energia eta momentuaren adierazpenak:

$$
E' = E - \mathbf{P.V} + \frac{1}{2} M V^2, \; \mathbf{P'} = \mathbf{P} - M \mathbf{v}
$${#eq-p8}

non $M$ fluidoaren masa den.

Kontsidera dezagun fluido bat, kapilar baten zehar higitzen dena $\mathbf{v}$ abiadurarekin. Fluidoa biskositatea badu, galdutako energia modelizatu ahal dugu higitzen den pertubazio baten moduan. Perturbazio honen energia eta momentua fluidoaren pausaguneko sisteman $\mathbf{p}$ eta $E_0 + \epsilon(\mathbf{p})$ izango dira, non $E_0$ pertubazioaren oinarrizko energia den eta $\epsilon(\mathbf{p})$ kitzikapenak sortutako energia. Kapilarraren pausaguneko sisteman ikusiko dugu:

$$
E' = E_0 + \epsilon(\mathbf{p}) + \mathbf{p.v} + \frac{1}{2} M v^2, \mathbf{P'} = \mathbf{p} + M \mathbf{v}
$${#eq-p9}

[@eq-p9] ikusi ahal dugu nola energia eta momentu aldaketak, kapilarraren pausaguneko sisteman, $\epsilon(\mathbf{p}) + \mathbf{p.v}$ eta $\mathbf{p}$ diren. Orduan, $\epsilon(\mathbf{p}) + \mathbf{p.v}$ negatiboa izan behar da berezko kitzikapena izateko. Hau posiblea izateko, $v > \epsilon(\mathbf{p}) / p$ izan behar da. Suposatzen badugu $\mathbf{p}$ momentua kapilarrari transferitzen diola, hau bero moduan disipatu egingo da eta fluidoa ez da egonkorra izango. Baina abiadura, 

$$
v_c = \text{min}_p \frac{\epsilon(\mathbf{p})}{p}
$${#eq-vc}

baino txikiago bada, kitzikapenak ezin dira agertu. Hau da Landauren superfluidotasunaren baldintza.

$$
v < v_c
$${#eq-LSC}

Fluidoaren eta kapilarraren abiadura erlatiboak, [@eq-vc] balio kritikoa baino txikiagoa bada. Orduna marruskadura gabeko fluxua izango dugu. Egoera honi, metaegonkorra deritzogu. Egonkorra da bat-bateko kitzikapenekiko.

Interakzio ahuleko Bose gasa Landauren irispidea betetzen du, non abiadura kritikoa soinuaren abiadura izango den. $^4He$-ren kasuan ere beteko egingo du Landauren irispidea, baina kasu honetan abiadura kritikoa soinuaren abiadura baino txikiagoa izango da, $^4He$ partikulen elkarrekintza handiagoa baita.

Demagun temperatura txikia dela. Gure fluidoaren propietateak izango dira interakzio gabeko gas baten kitzikapenak (kuasipartikulak) oreka termikoan bezalakoak. kuasipartikulak dira sistemaren masaren parte bat garraiatzen dituztenak. Gainera, hauek talka egitean kapilarraren hormekin energia disipatu egingo dute, fluido normal baten moduan. Beraz, izango ditugu bi fase, bat normala $\mathbf{v_n}$-rekin eta beste bat superfluidoa dena $\mathbf{v_s}$, non abiadura hauek izango dira kapilarraren pausaguneko sistemarekiko. Orduan kitzikapenen energia $\epsilon(\mathbf{p}) + \mathbf{p.}(\mathbf{v_s - v_n})$. Orekan dauden kitzikapenen, $\mathbf{p}$ banaketa funtzioa:

$$
N_{\mathbf{p}} = \left[ exp\left(\frac{\epsilon(\mathbf{p}) + \mathbf{p.} (\mathbf{v_s - v_n})}{k_B T}\right) - 1 \right]^{-1}
$${#eq-Np}

Ekuazio hau betetzeko $\mathbf{p}$-ren balio guztietarako (hau da, kitzikapenen energia positiboa izateko) $|\mathbf{v_s} - \mathbf{v_n}|$ abiadura kritikoa baino txikiagoa izan beharko da. Orduan, $N_\mathbf{p}$ beti izango da positiboa. Oreka termodinamikoan gaudenean, superfluido fasearen eta fase normalaren arteko marruskadurarik ez dago. Hau gertatzekotan, gero eta kitzikapen gehiago sortuko lirateke eta, ondorioz, superfluido fasea apurtuko zen.

Kontuan izanda bi faseak batera daudela, fluidoaren masa dentsitatea idatz dezakegu hurrengo moduan: $\rho = \rho_n + \rho_s$ ([@Pitaevskii] erabiltzen du $\rho = n m$ dentsitatea hemendik aurrera literatura orokorrean hau egiten baitenez, $n$ erabili beharrean). Likidoaren masa korrontea definitu dezakegu:

$$
m \mathbf{j} = \rho_s \mathbf{v_s} + \rho_n \mathbf{v_n}
$${#eq-mj}

Hau erabili ahal dugu definitzeko fluido normalaren dentsitatea. Jar gaitezen superfluidoaren pausaguneko sisteman, orduan $m\mathbf{j} = \rho_n \mathbf{v_n}$ izango dugu. Beraz, likidoak dakarren momentu osoa $\mathbf{P} = \sum_{\mathbf{p}} N_{\mathbf{p}} \mathbf{p}$ izango da. Onekin, [@eq-mj] berridatzi dezakegu:

$$
m \mathbf{j} = \int \; \frac{d \mathbf{p}}{(2 \pi \hbar)^3} \mathbf{p} N_{\mathbf{p}}
$${#eq-intmj}

eta esan dugunez, superfluidoaren pausaguneko sisteman gaudenez

$$
\rho_n \mathbf{v_n} = \int \; \frac{d \mathbf{p}}{(2 \pi \hbar)^3} \mathbf{p} N_{\mathbf{p}}
$${#eq-intrhov}

izango dugu. $\mathbf{v_n}$ txikia izango denez (oreka termikoan egoteko) $N_{\mathbf{p}}$ seriean garatu dezakegu termino linealerarte. Hau eginez, lortuko dugu fase normalaren masa dentsitatea

$$
\rho_n = - \frac{1}{3} \int \; \frac{d \mathbf{p}}{(2 \pi \hbar)^3} \frac{d N_{\mathbf{p}}(\epsilon)}{d \epsilon} p^2,
$${#eq-masadentitatea}

isotropikoa izango dena $\mathbf{p}$-rekiko. Oso erabilgarria da, kalkulatu ahal dugulako fase normalaren banaketa kitzikapenen funtzioen bitartez. Baina zenbait limite dauzkagu, $N_{\mathbf{p}}$ ez badago ondo definitua, desorden handia dogoenean, beste era bat bilatu beharko dugu kalkulatu ahal izateko fase normalaren dentsitatea.

### Bose-Einstein kondentsatua eta superfluidotasuna 

Orain nahi dugu BEC-aren eta superfluidoasunaren arteko erlazioa aztertu. Lehen egin dugun moduan, kondentsatuaren $\Psi_0$ uhin-funtzioaren propietateak aztertu nahi ditugu, transformazio Galilear bat egitean. Garrantzitsua da aipatzea, $|\Psi_0|^2$ dentsitatea uniformea izan arren, gure uhin-funtzioa ez da aldaezin bat izango transformazio Galilear batekiko fase bat gehitu beharko diogulako. Fase honen kalkulua egiteko erabili dezakegu [@eq-p1]. Erreza da baieztatzea

$$
\hat{\Psi}' = \hat{\Psi}(\mathbf{r-v}t,t) \exp \left[ \frac{i}{\hbar} \left( m \mathbf{v.r} - \frac{1}{2} m v^2 t \right) \right],
$${#eq-phiGalilear}

non $\mathbf{v}$ bektore konstante bat den, soluzio bat dela. Hau eremu eragilearen transformazio Galilearra da. ordena-parametroa eta bere itxarotako balio izango dute transformazio berbera. Dakigunez, gure fluidoa orekan dagoen erreferentzia sisteman, izango dugun uhin-funtzioa $\Psi_0 = \sqrt{n_0} e^{-i \mu t / \hbar}$, non $n_0$ $\mathbf{r}$-ren independiente den konstantea. Baina, fluidoa $\mathbf{v}$ abiadurarekin mugitzen den erreferentzia sisteman jarriz, lehen esan dugunez modulua es da aldatuko, fasea ez bezala. gure ordena-parametro berria $\Psi_0 = \sqrt{n_0} e^{iS}$ non gure fase berria

$$
S(\sqrt{r},t) = \frac{1}{\hbar} \left[ m \mathbf{v.r} - \left( \frac{1}{2} m v^2 + \mu \right) t \right]
$${#eq-6.15}

izango den. Gainera, Hamilton-Jacobi ekuazio batetik hasi garenez (Schrödinger-en ekuazioa), dakigu gure superfluidoaren abiadura fasearen paraleloa izango dela:

$$
\mathbf{v}_s = \frac{\hbar}{m} \nabla S.
$${#eq-p6.16}

Abiadura hau, era motelean aldatu ahal da denboran eta espazioan zehar. Gainera, guztiz orokorra da, ez baititugu inolako hurbilketak egin.

### Superfluidoen hidrodinamikaren teoria (T=0K)

Temperatura nulua denean, portaera makroskopikoa erakusten duen ekuazioa fluido irrotazional klasiko batena da. Kitzikapen termikoen gabezian, deskribatu dezakegu gure sistema bi parametroen menpe, superfluidoaren abiadurarekin eta bere masa dentsitatearekin. Masa dentsitatea lortuko dugu jarraitutasun ekuazioaren bitartez,

$$
\frac{\partial \rho}{t} + \text{div} (\mathbf{v}_s \rho) = 0
$${#eq-p6.17}

masaren kontserbazioa ezartzen duena. Abiadura eremuaren ekuazioa lortzeko, fasea [@eq-6.15] betetzen duela erabiliko dugu

$$
\hbar \frac{\partial S}{\partial t} = - \left( \frac{1}{2} m v^2 + \mu \right).
$${#eq-p6.18}

Aurreko atalean aurresan genuen bezala, ekuazio hau ez da bakarrik baliagarria orekan (biak denbora eta posizioarekiko menpekotasunik ez daukatenean), baizik eta hauek biak era motelean aldatzen direnean denbora eta espazioan zehar. Orduan, aurreko adierazpenaren gradientea hartuz eta [@eq-p6.16] adierazpena erabiliz lortuko dugu abiadura eremuaren adierazpena

$$
m \frac{\partial \mathbf{v}_s}{\partial t} + \nabla \left( \frac{1}{2} m \mathbf{v}_s^2 + \mu(\rho) \right) = 0
$${#eq-p6.19}

non potentziak kimikoa lokalki ebaluatzen da, kontuan izanda fluidoaren dentsitate puntuala. Konturatzen bagara, adierazpen honek Eulerren ekuazioaren antza dauka, baina kanpoko potentziala ez dagoenean. Beraz $V_{ext}$ bat gehitu ahal diogu

$$
m \frac{\partial \mathbf{v}_s}{\partial t} + \nabla \left( \frac{1}{2} m \mathbf{v}_s^2 + \mu(\rho) + V_{ext} \right) = 0.
$${#eq-p6.20}

Oinarrizko egoera aztertzean, hau da $\mathbf{v}_s = 0$ denean berreskuaretzen dugu Thomas-Fermiren limitea non potentzial kimikoa 

$$
\mu(\rho(\mathbf{r})) + V_{ext}(\mathbf{r}) = \mu_0
$${#eq-p6.21}

izango den.

### hidrodinamika kuantikoa

[@eq-p6.17] eta [@eq-p6.19] adierazpenak, fluidoaren oszilazio txikiak soinu uhinak direla adierazten dute. Mekanika kuantikoan, soinu uhin hauei fonoiak dira. Hau da, soinu uhinak ohiko erregelen bitartez kuantizatzean lortzen ditugun kuasipartikulak dira. Hidrodinamika klasikoaren ekuazioak kuantizatzeko, eremu klasikoak kuantizatu beharko ditugu. Hau erabilgarria izango da interakzio handiko Bose-Einstein kondentsatuak aztertzean.

Kuantizazio prozesua egiteko, Hamiltondar klasikoaren adierazpena lortzea izango da erabilgarria. Likido baten energia 

$$
H = \int \; d\mathbf{r} \left( \frac{\rho}{2} (\nabla \phi)^2 + e(\rho) \right),
$${#eq-p6.22}

non $\phi$ abiadura potentziala den $\mathbf{v}_s = \nabla \phi$ eran definitua, $\rho$ fluidoaren dentsitatea eta potentzial kimikoa sartu egin dugu fluidoaren bolumen unitateko energiaren bitartez $e(\rho)$; hauen arteko erlazioa $\mu = m \; de/d\rho$ izanda. Hamiltondarraren bariazioa eginez

$$
\delta H = \int \left[ -\text{div}(\rho \mathbf{v}_s) \delta \phi + \left( \frac{1}{2} (\nabla \phi)^2 + \frac{\mu(\rho)}{m} \right) \right]
$${#eq-p6.23}

lortzen da. Honen bitartez [@eq-p6.17] eta [@eq-p6.19] hurrengo eran jar daiteke:

$$
\frac{\partial \rho}{\partial t} = \frac{\delta H}{\delta \phi}, \; \frac{\partial \phi}{\partial t} = - \frac{\delta H}{\delta \rho},
$$

beraz argi dago $\phi \text{ eta } \rho$ gure problemaren aldagai konjokatuak direla. Landau 1941-tean, [@Landau1941Superfluidity] artikuluan, hurrengo trukatzailea proposatu zuen 

$$
[\hat{\phi}(\mathbf{r}), \hat{\rho}(\mathbf{r'})] = -i \hbar \delta(\mathbf{r} - \mathbf{r'}).
$${#eq-p6.24}

Era honetan pasatu gara hidrodinamika klasikotik, hidrodinamika kuantikora. Gainera fasea [@eq-p6.16] operadore batean bihurtu egiten da ere:

$$
\hat{S} = \frac{m}{\hbar} \hat{\phi}.
$${#eq-p6.25}

Hamiltondarra [@eq-p6.22], ondo simetrizatuz gero hermitikoa izan dadin, honela berridatzi dezakegu:

$$
\hat{H} = \int \left( \nabla \hat{\phi} \frac{\hat{\rho}}{2} \nabla \hat{\phi} + e(\hat{\rho}) \right) d\mathbf{r}
$${#eq-p6.26}

Hidrodinamika kuantikoa arazoak ditu sistema makroskopikoaren uhin bektore txikiak aztertzen ez ditugunean. Baina oso baliagarria da Bogoliubov-en teoria ezin denean erabili, adibidez, interakzio handiko BEC-tan gertatzen den moduan.

Helburua izango da, [@eq-p6.24] trukatzaile propietatea erabiltzea $\hat{\rho}$ eta $\hat{\phi}$ sortze ($\hat{b}$) eta deuseztatze ($\hat{b}^\dagger$) eragileen funtzioan adierazteko. Hau lortzeko, erabilgarria da erabiltzea masa dentsitatearen karga $\hat{\rho}' = \hat{\rho} - \rho_0$ non nahi duguna da jakitea zenbat aldatu den dentsitate lokala sistemaren dentsitate konstantearekiko. Beraz karga dentsitatearen adierazpena

$$
\hat{\rho}' = \frac{1}{\sqrt{2V}} \sum_{k \neq 0} A_k (\hat{b}_k e^{i\mathbf{k} \cdot \mathbf{r}} + \hat{b}_k^\dagger e^{-i\mathbf{k} \cdot \mathbf{r}})
$${#eq-p6.27}

izango da, non $V$ sistema osoaren bolumena den. $\hat{b}_k \text{ eta } \hat{b}_k^\dagger$ hurrengo erlazioa beteko dute

$$
\hat{b}_k \hat{b}_k^\dagger - \hat{b}_k^\dagger \hat{b}_k = \delta_{kk'},
$${#eq-p6.28}

$A_k$ koefizienteak aukeratu ditugu Hamiltondarra diagonala izateko. $\hat{\phi}$ eragilea [@eq-p6.24] erlazioa betetzeko

$$
\hat{\phi} = -\frac{1}{\sqrt{2V}} \sum_{k \neq 0} i\hbar (A_k)^{-1} (\hat{b}_k e^{i\mathbf{k} \cdot \mathbf{r}} - \hat{b}_k^\dagger e^{-i\mathbf{k} \cdot \mathbf{r}}).
$${#eq-p6.29}

[@eq-p6.26] Hamiltondarra garatzen badugu, termino lineala desagertu egingo da karkaren kontserbazioa dela eta. Orduan termino koadratikoa:

$$
H^{(2)} = \int \left( \frac{1}{2} \bar{\rho}(\nabla \hat{\phi})^2 + \frac{c^2}{2} \frac{\hat{\rho}^2}{\bar{\rho}} \right) d\mathbf{r},
$${#eq-p6.30}

non $c^2 = (\rho/m) d\mu/d\rho$ soinuaren abiadura den. [@eq-p6.27] eta [@eq-p6.29] aurreko adierazpenean ordezkatuz, lortuko dugu gire Hamiltondarraren forma diagonala

$$
H^{(2)} = \sum_k \hbar \omega_k \hat{b}_k^\dagger \hat{b}_k,
$${#eq-p6.31}

izango dela. [@eq-p6.31] bat dator $\omega_k = ck$ dispertsio erlazioa duten fonoien Hamiltondarrarekin. Gainera, $A_k$ koefizienteen adierazpena lortu dezakegu

$$
A_k = \left( \frac{\hbar k \bar{\rho}}{c} \right)^{1/2}.
$${#eq-p6.32}

### Superfluidoen biraketa eta bortize kuantizatuak

Superfluidoek, ezin dute solido zurrun gisa biratu. Biraketa bat lortuko du bortize kuantizatuen bitartez. Nahiz eta, bortize baten abiadura-eremua irrotazionala izan, bere zirkulazioa kuantizatuta dago:

$$
\oint \mathbf{v}_s \cdot d\mathbf{l} = 2\pi \frac{\hbar}{m} s, \quad (s \in \mathbb{Z}),
$${#eq-p6.89}

non $s$ bortizearen karga den. Hau behartzen du zirkulazioa $h/m$ unitateetan dagoela. Orduan bortez baten abiadura tangentziala:

$$
v_s = s \frac{\hbar}{m} \frac{1}{r}
$${#eq-p6.90}

non $r$ bortez-lerrotik dagoen distantzia den.

Bortize baten energia zinetikoa bere luzerarekiko, honela adieraz daiteke:

$$
E_v = L \pi \rho_s s^2 \left( \frac{\hbar}{m} \right)^2 \ln \left( \frac{R}{r_c} \right)
$${#eq-p6.92}

non $R$ sistemaren da eta $r_c$ bortizearen nukleoaren tamaina. Bortizea energetikoki baimendua egoteko, gure sistema osoa $\Omega$ abiadura angeluar minimo batekin biratu beharko du:

$$
\Omega_c = \frac{\hbar}{m R^2} \ln \left( \frac{R}{r_c} \right).
$${#eq-p6.93}

$\Omega$ gero eta handiagoa eginez gero, gero eta bortize gehiagoren zorrera ahalbidetzen da. Bortize kopuru maximoa $\Omega$ jakin batentzako:

$$
n_v = \frac{m}{\pi \hbar} \Omega
$${#eq-p6.95}

izango da.
